# Generated by Django 4.2.13 on 2025-12-11 05:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(help_text='Foydalanuvchi nomi', max_length=255, unique=True)),
                ('fullname', models.CharField(help_text='Foydalanuvchi FIO', max_length=100)),
                ('avatar', models.ImageField(blank=True, help_text='Profil rasmi', null=True, upload_to='avatars/%Y/%m/%d')),
                ('date_of_birthday', models.DateField(blank=True, help_text='Tug‘ilgan sanasi', null=True, verbose_name='date of birthday')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], help_text='Jinsi', max_length=6, null=True)),
                ('phone_number', models.CharField(help_text='Telefon raqami', max_length=100, verbose_name='Phone number')),
                ('email', models.EmailField(blank=True, help_text='Email manzili', max_length=254, null=True, verbose_name='email address')),
                ('points_balance', models.PositiveIntegerField(default=0, verbose_name='Баланс баллов')),
                ('is_full_name_completed', models.BooleanField(default=False)),
                ('is_phone_completed', models.BooleanField(default=False)),
                ('is_email_completed', models.BooleanField(default=False)),
                ('is_region_completed', models.BooleanField(default=False)),
                ('is_category_completed', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Реферальный код')),
                ('is_active', models.BooleanField(default=True, help_text='Foydalanuvchi holati', verbose_name='Active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Ro‘yxatdan o‘tgan sana', verbose_name='Date joined')),
                ('password', models.CharField(blank=True, help_text='Parol', max_length=255, null=True)),
                ('address', models.TextField(help_text='Yashash manzili', null=True, verbose_name='Address')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(help_text='Yaratgan foydalanuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(help_text='Tuman', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_district', to='directory.district')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Кем приглашён')),
                ('region', models.ForeignKey(help_text='Viloyat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_region', to='directory.region')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Company Code', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Company name', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Company holati', verbose_name='Active')),
                ('phone', models.CharField(help_text='Telefon raqami', max_length=100, verbose_name='Phone number')),
                ('address', models.TextField(help_text='Yashash manzili', null=True, verbose_name='Address')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='Yangilangan vaqt')),
                ('created_by', models.ForeignKey(help_text='Yaratgan foydalanuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_created', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(help_text='Tuman', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_district', to='directory.district')),
                ('region', models.ForeignKey(help_text='Viloyat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_region', to='directory.region')),
                ('updated_by', models.ForeignKey(help_text='Yangilagan foydalanuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, verbose_name='Module name')),
                ('on_dashboard', models.BooleanField(default=False)),
                ('sorting', models.IntegerField(blank=True, null=True)),
                ('content_types', models.ManyToManyField(to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text='Foydalanuvchi roli', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_user', to='users.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_by',
            field=models.ForeignKey(help_text='Yangilagan foydalanuvchi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
