# Generated by Django 4.2.13 on 2025-12-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('checked_out', 'Yakunlangan'), ('canceled', 'Bekor qilingan')], default='open', max_length=20, verbose_name='Status')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Hisob-kitobni tezlashtirish uchun denormalizatsiya', verbose_name='Jami ball')),
            ],
            options={
                'verbose_name': 'Savatcha',
                'verbose_name_plural': 'Savatchalar',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('item_points', models.PositiveIntegerField(default=0, help_text='product.price_points * quantity', verbose_name='Jami ball')),
            ],
            options={
                'verbose_name': 'Savatcha elementi',
                'verbose_name_plural': 'Savatcha elementlari',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('reason', models.CharField(choices=[('qr_scan', 'QR skan'), ('market_purchase', 'Marketdan xarid'), ('raffle_play', 'Розыгрышда ishtirok'), ('referral_bonus', 'Referal bonus'), ('profile_bonus', 'Profilni to‘ldirish bonusi'), ('other', 'Boshqa')], default='other', max_length=32, verbose_name='Sabab')),
                ('amount', models.IntegerField(help_text='Musbat – qo‘shiladi, manfiy – ayriladi', verbose_name='Miqdori')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Ball tranzaksiyasi',
                'verbose_name_plural': 'Ball tranzaksiyalari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('type', models.CharField(choices=[('market', 'Market'), ('raffle', 'Розыгрыш')], default='market', max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Qisqa tavsif')),
                ('image', models.ImageField(upload_to='burn/products/%Y/%m/%d')),
                ('price_points', models.PositiveIntegerField(verbose_name='Ball narxi')),
                ('old_price_points', models.PositiveIntegerField(blank=True, help_text='Chegirma ko‘rsatish uchun', null=True, verbose_name='Eski ball narxi')),
                ('is_one_size', models.BooleanField(default=False, help_text='“Один размер” tugmasi uchun', verbose_name='Bitta o‘lcham')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Ombordagi soni')),
                ('is_limited', models.BooleanField(default=False, verbose_name='Limited')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
            },
        ),
        migrations.CreateModel(
            name='QRReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('code', models.CharField(help_text='Skan qilinganda botga keladigan kod', max_length=255, unique=True, verbose_name='QR kodi yoki token')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Beriladigan ballar')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal ishlatish soni')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Necha marta ishlatilgan')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'QR mukofoti',
                'verbose_name_plural': 'QR mukofotlari',
            },
        ),
        migrations.CreateModel(
            name='QRScanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='Berilgan ballar')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='Skan qilingan vaqt')),
            ],
            options={
                'verbose_name': 'QR skan tarixi',
                'verbose_name_plural': 'QR skan tarixi',
            },
        ),
        migrations.CreateModel(
            name='QRTutorialSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='burn/qr_tutorial/%Y/%m/%d')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'QR bo‘yicha slayd',
                'verbose_name_plural': 'QR bo‘yicha slaydlar',
                'ordering': ['order'],
            },
        ),
    ]
