# Generated by Django 4.2.13 on 2025-12-11 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('directory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtutorialslide',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrtutorialslide',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrscanhistory',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrscanhistory',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='shop.qrreward', verbose_name='Mukofot'),
        ),
        migrations.AddField(
            model_name='qrscanhistory',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrscanhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='qrreward',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrreward',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='directory.productcategory', verbose_name='Kategoriya'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='directory.productsize', verbose_name='Mavjud o‘lchamlar'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='faq',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faq',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart', verbose_name='Savatcha'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product', verbose_name='Mahsulot'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='directory.productsize', verbose_name='O‘lcham'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
