# Generated by Django 4.2.13 on 2025-12-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extend_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Extended name')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('instance', models.CharField(blank=True, max_length=255, null=True)),
                ('instance_id', models.BigIntegerField(blank=True, null=True)),
                ('field_name', models.TextField(blank=True, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=16, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('term_name', models.CharField(max_length=500, verbose_name='Term name')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('name_en', models.CharField(max_length=500, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=500, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=500, null=True, verbose_name='Name')),
            ],
            options={
                'ordering': ('id',),
                'get_latest_by': 'created_time',
                'abstract': False,
            },
        ),
    ]
