# Generated by Django 4.2.13 on 2025-12-11 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationterm',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationterm',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelaudit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extendedcontenttype',
            name='content_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
