# Generated by Django 4.2.13 on 2025-12-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('code', models.CharField(blank=True, help_text='Mamlakat kodi', max_length=50, null=True, verbose_name='Country code')),
                ('name', models.CharField(blank=True, help_text='Mamlakat nomi', max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, help_text='Mamlakat nomi', max_length=255, null=True)),
                ('name_uz', models.CharField(blank=True, help_text='Mamlakat nomi', max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, help_text='Mamlakat nomi', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('code', models.CharField(blank=True, help_text='Tuman kodi', max_length=50, null=True, verbose_name='District code')),
                ('name', models.CharField(blank=True, help_text='Tuman nomi', max_length=255, null=True, verbose_name='District name')),
                ('name_en', models.CharField(blank=True, help_text='Tuman nomi', max_length=255, null=True, verbose_name='District name')),
                ('name_uz', models.CharField(blank=True, help_text='Tuman nomi', max_length=255, null=True, verbose_name='District name')),
                ('name_ru', models.CharField(blank=True, help_text='Tuman nomi', max_length=255, null=True, verbose_name='District name')),
                ('geo_json', models.TextField(blank=True, help_text='Geo json', verbose_name='GeoJson')),
            ],
            options={
                'verbose_name': 'district',
                'verbose_name_plural': 'districts',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('name', models.CharField(max_length=255, verbose_name='Kategoriya nomi')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Mahsulot kategoriyasi',
                'verbose_name_plural': 'Mahsulot kategoriyalari',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('label', models.CharField(max_length=50, verbose_name='O‘lcham')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'O‘lcham',
                'verbose_name_plural': 'O‘lchamlar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='Yaratilgan vaqt')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text="O'zgartirilgan vaqt")),
                ('code', models.CharField(blank=True, help_text='Viloyat kodi', max_length=50, null=True, verbose_name='Region code')),
                ('name', models.CharField(blank=True, help_text='Viloyat nomi', max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, help_text='Viloyat nomi', max_length=255, null=True)),
                ('name_uz', models.CharField(blank=True, help_text='Viloyat nomi', max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, help_text='Viloyat nomi', max_length=255, null=True)),
                ('geo_json', models.TextField(blank=True, help_text='Deo json', verbose_name='GeoJson')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
    ]
