# Generated by Django 4.2.13 on 2025-12-11 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsize',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productsize',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(blank=True, help_text="Viloyat jadvali bilan bog'lanish", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='districts', to='directory.region'),
        ),
        migrations.AddField(
            model_name='district',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(help_text="Kim yaratdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='country',
            name='updated_by',
            field=models.ForeignKey(help_text="Kim o'zgartirdi (User bilan bog'lanadi)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(model_name)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
